#!/usr/bin/env python3
"""
Generates Meal Mapper's adaptive launcher icon (a top-down thali) as Android vector drawables, plus an SVG/PNG
preview. One source of truth for all layers. Run: python3 tools/icon/make_icon.py
Canvas 108x108 (adaptive icon); keep artwork inside the 66 dp safe circle (radius 33 around 54,54).
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "app/src/main/res"


def circle(cx, cy, r):
    return f"M{cx - r},{cy}a{r},{r} 0 1,0 {2 * r},0a{r},{r} 0 1,0 {-2 * r},0z"


def ellipse(cx, cy, rx, ry):
    return f"M{cx - rx},{cy}a{rx},{ry} 0 1,0 {2 * rx},0a{rx},{ry} 0 1,0 {-2 * rx},0z"


PIN = "M63,48.2c-2.6,0 -4.7,2.1 -4.7,4.6c0,3.5 4.7,8 4.7,8s4.7,-4.5 4.7,-8c0,-2.5 -2.1,-4.6 -4.7,-4.6z"

# (path, fill, stroke, stroke_width, alpha) drawn in order
FOREGROUND = [
    (circle(54, 56.5, 31), "#000000", None, 0, 0.22),            # soft shadow
    (circle(54, 54, 31), "#F4ECDF", "#D8B26A", 2.6, 1),          # brass-rimmed plate
    (circle(54, 54, 26.5), None, "#E7DAC2", 1.0, 1),             # inner ring
    (circle(41.5, 44.5, 7.2), "#F2B84B", "#C9A55E", 1.5, 1),     # dal
    (circle(54, 38.8, 7.2), "#C4502F", "#C9A55E", 1.5, 1),       # curry
    (circle(66.5, 44.5, 7.2), "#6E9F4E", "#C9A55E", 1.5, 1),     # sabzi
    (circle(47.5, 61, 8.6), "#E6BA70", "#C38A3E", 1.1, 1),       # roti (under)
    (circle(44.5, 64.5, 8.6), "#D9A355", "#B97F35", 1.2, 1),     # roti (top)
    (circle(41.8, 62.2, 1.0), "#B0722C", None, 0, 1),
    (circle(46.6, 66.8, 1.1), "#B0722C", None, 0, 1),
    (circle(44.0, 68.4, 0.8), "#B0722C", None, 0, 1),
    (circle(47.8, 62.4, 0.7), "#B0722C", None, 0, 1),
    (ellipse(63.5, 64.5, 9, 6.6), "#FFFFFF", "#E5D9C3", 1.0, 1), # rice
    (PIN, "#1E4636", None, 0, 1),                                # map pin on the rice
    (circle(63, 52.9, 1.6), "#F4ECDF", None, 0, 1),
]

MONOCHROME = [
    (circle(54, 54, 30), None, "#FFFFFF", 3.2, 1),
    (circle(41.5, 44.5, 7.2), "#FFFFFF", None, 0, 1),
    (circle(54, 38.8, 7.2), "#FFFFFF", None, 0, 1),
    (circle(66.5, 44.5, 7.2), "#FFFFFF", None, 0, 1),
    (circle(44.5, 64.5, 8.6), "#FFFFFF", None, 0, 1),
    (ellipse(63.5, 64.5, 9, 6.6), "#FFFFFF", None, 0, 1),
]

BG_TOP, BG_BOTTOM = "#2E6E51", "#143528"


def vector(shapes):
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           '<!-- Generated by tools/icon/make_icon.py. Edit the script, not this file. -->',
           '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
           '    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">']
    for d, fill, stroke, sw, alpha in shapes:
        attrs = [f'android:pathData="{d}"']
        if fill:
            attrs.append(f'android:fillColor="{fill}"')
            if alpha != 1:
                attrs.append(f'android:fillAlpha="{alpha}"')
        if stroke:
            attrs += [f'android:strokeColor="{stroke}"', f'android:strokeWidth="{sw}"']
        out.append("    <path " + " ".join(attrs) + " />")
    out.append("</vector>")
    return "\n".join(out) + "\n"


BACKGROUND = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/icon/make_icon.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="linear" android:startX="0" android:startY="0" android:endX="108" android:endY="108"
                android:startColor="{BG_TOP}" android:endColor="{BG_BOTTOM}" />
        </aapt:attr>
    </path>
</vector>
'''


def svg(shapes, size=432, mask=True):
    body = [f'<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{BG_TOP}"/>'
            f'<stop offset="1" stop-color="{BG_BOTTOM}"/></linearGradient>'
            '<clipPath id="c"><circle cx="54" cy="54" r="54"/></clipPath></defs>',
            '<g clip-path="url(#c)">' if mask else "<g>",
            '<rect width="108" height="108" fill="url(#g)"/>']
    for d, fill, stroke, sw, alpha in shapes:
        body.append(f'<path d="{d}" fill="{fill or "none"}" fill-opacity="{alpha}" '
                    f'stroke="{stroke or "none"}" stroke-width="{sw}"/>')
    body.append("</g>")
    return f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" viewBox="0 0 108 108">{"".join(body)}</svg>'


if __name__ == "__main__":
    (RES / "drawable/ic_launcher_foreground.xml").write_text(vector(FOREGROUND))
    (RES / "drawable/ic_launcher_monochrome.xml").write_text(vector(MONOCHROME))
    (RES / "drawable/ic_launcher_background.xml").write_text(BACKGROUND)
    (ROOT / "tools/icon/preview.svg").write_text(svg(FOREGROUND))
    print("icon written")
